services:
  pymongo_api:
    container_name: t3-pymongo_api
    build:
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - t3-mongodb1
    ports:
      - 8080:8080
    networks:
      app-network:
        ipv4_address: 173.17.1.20
    environment:
      MONGODB_URL: "mongodb://t3-mongodb1:27020"
      MONGODB_DATABASE_NAME: "somedb"

  t3-configSrv:
    image: mongo:latest # docker образ
    container_name: t3-configSrv
    restart: always
    ports:
      - "27017:27017"
    networks:
      app-network:
        ipv4_address: 173.17.1.10
    volumes:
      - t3-config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  t3-mongodb1-shard1:
    image: mongo:latest
    container_name: t3-mongodb1-shard1
    restart: always
    ports:
      - "27018:27018"
    networks:
      app-network:
        ipv4_address: 173.17.1.11
    volumes:
      - t3-mongodb1-shard1-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "t3-mongodb1-shard1-rs",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  t3-mongodb1-shard1-repl1:
    image: mongo:latest
    container_name: t3-mongodb1-shard1-repl1
    restart: always
    ports:
      - "27025:27025"
    networks:
      app-network:
        ipv4_address: 173.17.1.12
    volumes:
      - t3-mongodb1-shard1-repl1-data:/data/db
    command:
      [
        "--replSet",
        "t3-mongodb1-shard1-rs",
        "--bind_ip_all",
        "--port",
        "27025"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  t3-mongodb1-shard1-repl2:
    image: mongo:latest
    container_name: t3-mongodb1-shard1-repl2
    restart: always
    ports:
      - "27026:27026"
    networks:
      app-network:
        ipv4_address: 173.17.1.13
    volumes:
      - t3-mongodb1-shard1-repl2-data:/data/db
    command:
      [
        "--replSet",
        "t3-mongodb1-shard1-rs",
        "--bind_ip_all",
        "--port",
        "27026"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  t3-mongodb1-shard2:
    image: mongo:latest
    container_name: t3-mongodb1-shard2
    restart: always
    ports:
      - "27019:27019"
    networks:
      app-network:
        ipv4_address: 173.17.1.14
    volumes:
      - t3-mongodb1-shard2-data:/data/db
    command:
      [
        "--shardsvr",
        "--replSet",
        "t3-mongodb1-shard2-rs",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  t3-mongodb1-shard2-repl1:
    image: mongo:latest
    container_name: t3-mongodb1-shard2-repl1
    restart: always
    ports:
      - "27027:27027"
    networks:
      app-network:
        ipv4_address: 173.17.1.15
    volumes:
      - t3-mongodb1-shard2-repl1-data:/data/db
    command:
      [
        "--replSet",
        "t3-mongodb1-shard2-rs",
        "--bind_ip_all",
        "--port",
        "27027"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  t3-mongodb1-shard2-repl2:
    image: mongo:latest
    container_name: t3-mongodb1-shard2-repl2
    restart: always
    ports:
      - "27028:27028"
    networks:
      app-network:
        ipv4_address: 173.17.1.16
    volumes:
      - t3-mongodb1-shard2-repl2-data:/data/db
    command:
      [
        "--replSet",
        "t3-mongodb1-shard2-rs",
        "--bind_ip_all",
        "--port",
        "27028"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  t3-mongodb1:
    image: mongo:latest
    container_name: t3-mongodb1
    restart: always
    ports:
      - "27020:27020"
    networks:
      app-network:
        ipv4_address: 173.17.1.17
    command:
      [
        "mongos",
        "--configdb",
        "config_server/t3-configSrv:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

networks:
  app-network:
    name: t3-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 173.17.1.0/24

name: mongo-sharding-repl
volumes:
  t3-config-data:
  t3-mongodb1-shard1-data:
  t3-mongodb1-shard1-repl1-data:
  t3-mongodb1-shard1-repl2-data:
  t3-mongodb1-shard2-data:
  t3-mongodb1-shard2-repl1-data:
  t3-mongodb1-shard2-repl2-data: